### ISSUE TITLE
Error running the script

### ISSUE THREAD

**Issue by wanghaodawn** [jiamingzhang94/Adversarial-Prompt-Tuning#2]
I tried source scripts/main.sh in the main directory, are there any further configs I am missing?

Here are errors:

Traceback (most recent call last):
  File "train.py", line 6, in <module>
    from dass.engine import build_trainer
  File "/root/Adversarial-Prompt-Tuning/dass/engine/__init__.py", line 2, in <module>
    from .trainer import TrainerX, TrainerXU, TrainerBase, SimpleTrainer, SimpleNet  # isort:skip
  File "/root/Adversarial-Prompt-Tuning/dass/engine/trainer.py", line 22, in <module>
    from attack.purification import super_resolution
  File "/root/Adversarial-Prompt-Tuning/attack/purification.py", line 12, in <module>
    import runners.utils as utils
ModuleNotFoundError: No module named 'runners'
--------------------------------------------------------------------------------------
zero shot
Traceback (most recent call last):
  File "train.py", line 6, in <module>
    from dass.engine import build_trainer
  File "/root/Adversarial-Prompt-Tuning/dass/engine/__init__.py", line 2, in <module>
    from .trainer import TrainerX, TrainerXU, TrainerBase, SimpleTrainer, SimpleNet  # isort:skip
  File "/root/Adversarial-Prompt-Tuning/dass/engine/trainer.py", line 22, in <module>
    from attack.purification import super_resolution
  File "/root/Adversarial-Prompt-Tuning/attack/purification.py", line 12, in <module>
    import runners.utils as utils
ModuleNotFoundError: No module named 'runners'

**Comment by jiamingzhang94** [comment]
This is the code for Adversarial Purification. You can comment out the code involving 'runners' for now. I will fix it in the future.

**Comment by wanghaodawn** [comment]
I see, thanks for the quick response and clarification. There is one further error. In directory 'Adversarial-Prompt-Tuning/configs/trainers/' there is only one folder called AdvPT, but it seems that we need ADV folder. Here is the message:

zero shot
Traceback (most recent call last):
  File "/root/Adversarial-Prompt-Tuning/train.py", line 229, in <module>
    main(args)
  File "/root/Adversarial-Prompt-Tuning/train.py", line 122, in main
    cfg = setup_cfg(args)
  File "/root/Adversarial-Prompt-Tuning/train.py", line 108, in setup_cfg
    cfg.merge_from_file(args.config_file)
  File "/root/miniconda3/lib/python3.10/site-packages/yacs/config.py", line 211, in merge_from_file
    with open(cfg_filename, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/root/Adversarial-Prompt-Tuning/configs/trainers/ADV/vit_l14.yaml

**Comment by jiamingzhang94** [comment]
This is a typo, you can directly change ADV to AdvPT to correct it. If there are any similar errors, please report them.

**Comment by wanghaodawn** [comment]
```
robust acc:
Traceback (most recent call last):
  File "/root/Adversarial-Prompt-Tuning/train.py", line 229, in <module>
    main(args)
  File "/root/Adversarial-Prompt-Tuning/train.py", line 145, in main
    trainer.before_adv_test()
  File "/root/Adversarial-Prompt-Tuning/dass/engine/trainer.py", line 525, in before_adv_test
    torch.save(self.test_pkl, pkl_path)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/serialization.py", line 618, in save
    with _open_zipfile_writer(f) as opened_zipfile:
  File "/root/miniconda3/lib/python3.10/site-packages/torch/serialization.py", line 492, in _open_zipfile_writer
    return container(name_or_buffer)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/serialization.py", line 463, in __init__
    super().__init__(torch._C.PyTorchFileWriter(self.name))
RuntimeError: Parent directory ~/Adversarial-Prompt-Tuning/test does not exist.
```

I noticed that there are these configs of path and directory are hard coded, do you have any suggestions on these variables? 

```
DIR=/share/test/user/share1/new/${DATASET}/${TRAINER}/${CFG}/adv

pkl_path = '/share/test/user/share1/train/{}_{}.pkl'.format(self.cfg.DATASET.NAME,

pkl_path = '/share/test/user/share1/test/{}_{}_{}.pkl'.format(self.cfg.DATASET.NAME,
```

**Comment by jiamingzhang94** [comment]
These mechanisms seem to be written in the CoOp framework, sorry I can’t help you.

**Comment by HashmatShadab** [comment]
> This is the code for Adversarial Purification. You can comment out the code involving 'runners' for now. I will fix it in the future.

When will this fix be provided???
